package ui.login;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Acer
 */
import ui.member.MemberDashboard;
import ui.admin.AdminDashboard;

import dao.UserDAO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class LoginFrame extends javax.swing.JFrame {
    

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tagline = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(244, 246, 249));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224)));
        jPanel1.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Gemini_Generated_Image_f9olygf9olygf9ol.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(-30, 0, 550, 870);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 520, 870);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224), 2));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(47, 128, 237));
        jLabel5.setText("Login to Your Account");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(290, 430, 310, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Username");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(290, 490, 100, 38);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Password");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(290, 590, 100, 38);

        txtUsername.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUsername.addActionListener(this::txtUsernameActionPerformed);
        jPanel2.add(txtUsername);
        txtUsername.setBounds(390, 490, 350, 38);

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel2.add(txtPassword);
        txtPassword.setBounds(390, 590, 350, 38);

        btnLogin.setBackground(new java.awt.Color(47, 128, 237));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setRequestFocusEnabled(false);
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        jPanel2.add(btnLogin);
        btnLogin.setBounds(390, 670, 350, 42);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel7.setText("Forgot Password?");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(510, 710, 140, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 128, 237));
        jLabel1.setText("ClubHub Login");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(430, 80, 200, 38);

        tagline.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tagline.setForeground(new java.awt.Color(102, 102, 102));
        tagline.setText("Manage your club efficiently");
        jPanel2.add(tagline);
        tagline.setBounds(430, 120, 210, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Gemini_Generated_Image_gntjs5gntjs5gntj.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(410, 150, 250, 260);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(520, 0, 1020, 870);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    

    String username = txtUsername.getText();
    String password = new String(txtPassword.getPassword());

    UserDAO dao = new UserDAO();
    String role = dao.validateUser(username, password);

        if (role == null) {
        JOptionPane.showMessageDialog(this, "Invalid Username or Password");
        } 
        else if (role.equals("admin")) {
        AdminDashboard ad = new AdminDashboard(username);
        ad.setVisible(true);
        dispose();
        } 
        else {
        MemberDashboard md = new MemberDashboard(username);
        md.setVisible(true);
        dispose();
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new LoginFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel tagline;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
