/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.admin;

import javax.swing.JFrame;

/**
 *
 * @author Acer
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     * @param username
     */
    public AdminDashboard(String username) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
         lblWelcome.setText("Welcome, " + username + "!");
         showPanel(new DashboardPanel());
    }
    
     private void showPanel(javax.swing.JPanel panel) {

    contentPanel.removeAll();

    contentPanel.setLayout(new java.awt.BorderLayout());

    contentPanel.add(panel, java.awt.BorderLayout.CENTER);

    contentPanel.revalidate();

    contentPanel.repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        sidepanel = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(47, 128, 237));
        lblWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user .png"))); // NOI18N
        lblWelcome.setText("Welcome");
        getContentPane().add(lblWelcome);
        lblWelcome.setBounds(680, 20, 220, 40);

        sidepanel.setBackground(new java.awt.Color(47, 128, 237));
        sidepanel.setLayout(null);

        jButton4.setBackground(new java.awt.Color(47, 128, 237));
        jButton4.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        jButton4.setText("LogOut");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton4.setIconTextGap(40);
        sidepanel.add(jButton4);
        jButton4.setBounds(0, 480, 240, 50);

        jButton3.setBackground(new java.awt.Color(47, 128, 237));
        jButton3.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home-button.png"))); // NOI18N
        jButton3.setText("Dashboard");
        jButton3.setBorder(null);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton3.setIconTextGap(40);
        jButton3.addActionListener(this::jButton3ActionPerformed);
        sidepanel.add(jButton3);
        jButton3.setBounds(10, 60, 230, 50);

        jButton2.setBackground(new java.awt.Color(47, 128, 237));
        jButton2.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calendar (1).png"))); // NOI18N
        jButton2.setText("Events");
        jButton2.setBorder(null);
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton2.setIconTextGap(40);
        sidepanel.add(jButton2);
        jButton2.setBounds(10, 160, 230, 50);

        jButton1.setBackground(new java.awt.Color(47, 128, 237));
        jButton1.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user (2).png"))); // NOI18N
        jButton1.setText("Members");
        jButton1.setBorder(null);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton1.setIconTextGap(40);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        sidepanel.add(jButton1);
        jButton1.setBounds(10, 110, 230, 50);

        jButton5.setBackground(new java.awt.Color(47, 128, 237));
        jButton5.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/business-report.png"))); // NOI18N
        jButton5.setText("Reports");
        jButton5.setBorder(null);
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton5.setIconTextGap(30);
        sidepanel.add(jButton5);
        jButton5.setBounds(20, 210, 220, 50);

        getContentPane().add(sidepanel);
        sidepanel.setBounds(0, 70, 240, 530);

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229)));
        contentPanel.setLayout(null);
        getContentPane().add(contentPanel);
        contentPanel.setBounds(240, 70, 660, 530);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo small.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 70, 70);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(47, 128, 237));
        jLabel4.setText("CLUBHUB");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 0, 190, 40);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(47, 128, 237));
        jLabel3.setText("Manage your club effectively.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 30, 340, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/info.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(650, 20, 20, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        showPanel(new MemberPanel());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         showPanel(new DashboardPanel());
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     * @param username
     */
    public static void main(String args[], String username) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminDashboard(username).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel sidepanel;
    // End of variables declaration//GEN-END:variables
}
