/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.admin;

import javax.swing.JFrame;

/**
 *
 * @author Acer
 */
public class MemberManagement extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MemberManagement.class.getName());

    /**
     * Creates new form MemberManagement
     */
    public MemberManagement() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        txtPosition = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtSearch = new javax.swing.JPasswordField();
        btnClear = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtPassword1 = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMembers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 128, 237));
        jLabel1.setText("ClubHub - Member Management");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 490, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(47, 128, 237));
        jLabel2.setText("Search");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 360, 90, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(47, 128, 237));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 90, 60, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(47, 128, 237));
        jLabel4.setText("E-Mail");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 120, 60, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(47, 128, 237));
        jLabel5.setText("Phone");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 150, 60, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(47, 128, 237));
        jLabel6.setText("Position");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 180, 70, 25);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(47, 128, 237));
        jLabel7.setText("Username");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 210, 90, 25);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(190, 120, 300, 22);
        getContentPane().add(txtName);
        txtName.setBounds(190, 90, 300, 22);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(190, 120, 300, 22);
        getContentPane().add(txtPhone);
        txtPhone.setBounds(190, 150, 300, 22);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(190, 150, 300, 22);
        getContentPane().add(txtPosition);
        txtPosition.setBounds(190, 180, 300, 20);
        getContentPane().add(txtUsername);
        txtUsername.setBounds(190, 210, 300, 20);
        getContentPane().add(txtSearch);
        txtSearch.setBounds(190, 360, 300, 22);

        btnClear.setBackground(new java.awt.Color(47, 128, 237));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("CLEAR");
        getContentPane().add(btnClear);
        btnClear.setBounds(520, 290, 100, 23);

        btnAdd.setBackground(new java.awt.Color(47, 128, 237));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        getContentPane().add(btnAdd);
        btnAdd.setBounds(190, 290, 100, 23);

        btnUpdate.setBackground(new java.awt.Color(47, 128, 237));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(300, 290, 100, 23);

        btnDelete.setBackground(new java.awt.Color(47, 128, 237));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        getContentPane().add(btnDelete);
        btnDelete.setBounds(410, 290, 100, 23);

        jSeparator1.setBackground(new java.awt.Color(47, 128, 237));
        jSeparator1.setForeground(new java.awt.Color(48, 48, 48));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 400, 900, 20);

        jSeparator2.setBackground(new java.awt.Color(47, 128, 237));
        jSeparator2.setForeground(new java.awt.Color(48, 48, 48));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 60, 900, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(47, 128, 237));
        jLabel8.setText("Password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 240, 90, 25);
        getContentPane().add(txtPassword1);
        txtPassword1.setBounds(190, 240, 300, 22);

        jSeparator3.setBackground(new java.awt.Color(47, 128, 237));
        jSeparator3.setForeground(new java.awt.Color(48, 48, 48));
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(0, 350, 900, 10);

        tblMembers.setBackground(new java.awt.Color(47, 128, 237));
        tblMembers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblMembers.setForeground(new java.awt.Color(255, 255, 255));
        tblMembers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "EMAIL", "POSITION"
            }
        ));
        jScrollPane1.setViewportView(tblMembers);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(2, 402, 900, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MemberManagement().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tblMembers;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JPasswordField txtSearch;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
