/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.admin;

/**
 *
 * @author Acer
 */

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import model.Member;
import service.MemberService;
public class MemberPanel extends javax.swing.JPanel {

    /**
     * Creates new form MemberPanel
     */
    private int selectedMemberId = -1;
    public MemberPanel() {
        initComponents();
        loadMemberTable();
         btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        
    }
    
    private void loadMemberTable() {

    MemberService service = new MemberService();

    ArrayList<Member> memberList = service.getAllMembers();

    DefaultTableModel model = (DefaultTableModel) tblMembers.getModel();

    model.setRowCount(0);

    for (Member member : memberList) {

        model.addRow(new Object[]{
            member.getMemberId(),
            member.getFullName(),
            member.getEmail(),
            member.getPhone(),
            member.getPosition(),
            member.getUsername()
        });

    }

}
    
    private void clearFields() {

    txtFullName.setText("");
    txtEmail.setText("");
    txtPhone.setText("");
    txtPosition.setText("");
    txtUsername.setText("");
    txtPassword.setText("");

    selectedMemberId = -1;

    btnAdd.setEnabled(true);
    btnUpdate.setEnabled(false);
    btnDelete.setEnabled(false);

    txtFullName.requestFocus();

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtPosition = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMembers = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 128, 237));
        jLabel1.setText("Members Management");
        add(jLabel1);
        jLabel1.setBounds(10, 10, 280, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Password");
        add(jLabel2);
        jLabel2.setBounds(30, 210, 70, 20);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Full Name");
        add(jLabel3);
        jLabel3.setBounds(30, 60, 70, 20);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Phone");
        add(jLabel4);
        jLabel4.setBounds(30, 90, 70, 20);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Email");
        add(jLabel5);
        jLabel5.setBounds(30, 120, 70, 20);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Position");
        add(jLabel6);
        jLabel6.setBounds(30, 150, 70, 20);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Username");
        add(jLabel7);
        jLabel7.setBounds(30, 180, 70, 20);

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtEmail);
        txtEmail.setBounds(130, 120, 230, 26);

        txtFullName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtFullName);
        txtFullName.setBounds(130, 60, 230, 26);

        txtPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtPhone);
        txtPhone.setBounds(130, 90, 230, 26);

        txtPosition.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtPosition);
        txtPosition.setBounds(130, 150, 230, 26);

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtUsername);
        txtUsername.setBounds(130, 180, 230, 26);

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtPassword);
        txtPassword.setBounds(130, 210, 230, 26);

        btnDelete.setBackground(new java.awt.Color(47, 128, 237));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        add(btnDelete);
        btnDelete.setBounds(310, 250, 90, 23);

        btnUpdate.setBackground(new java.awt.Color(47, 128, 237));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        add(btnUpdate);
        btnUpdate.setBounds(210, 250, 90, 23);

        btnAdd.setBackground(new java.awt.Color(47, 128, 237));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        add(btnAdd);
        btnAdd.setBounds(130, 250, 72, 23);

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setText("Search");
        add(jLabel8);
        jLabel8.setBounds(30, 300, 50, 20);
        add(jTextField1);
        jTextField1.setBounds(30, 320, 190, 30);

        btnClear.setBackground(new java.awt.Color(47, 128, 237));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("CLEAR");
        btnClear.addActionListener(this::btnClearActionPerformed);
        add(btnClear);
        btnClear.setBounds(410, 250, 72, 23);

        btnSearch.setBackground(new java.awt.Color(47, 128, 237));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search (1).png"))); // NOI18N
        add(btnSearch);
        btnSearch.setBounds(230, 320, 30, 30);
        add(jSeparator1);
        jSeparator1.setBounds(10, 40, 640, 10);
        add(jSeparator2);
        jSeparator2.setBounds(10, 290, 640, 10);

        tblMembers.setBackground(new java.awt.Color(47, 128, 237));
        tblMembers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229)));
        tblMembers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Full Name", "Email", "Phone", "Position", "Username"
            }
        ));
        tblMembers.setGridColor(new java.awt.Color(255, 255, 255));
        tblMembers.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tblMembers.setSelectionForeground(new java.awt.Color(47, 128, 237));
        tblMembers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMembersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMembers);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 372, 660, 160);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
         if (txtFullName.getText().trim().isEmpty()
            || txtEmail.getText().trim().isEmpty()
            || txtUsername.getText().trim().isEmpty()
            || txtPassword.getPassword().length == 0) {

        JOptionPane.showMessageDialog(this,
                "Please fill in all required fields.");

        return;   // Stop here if validation fails
    }
         Member member = new Member();

    member.setFullName(txtFullName.getText());
    member.setEmail(txtEmail.getText());
    member.setPhone(txtPhone.getText());
    member.setPosition(txtPosition.getText());
    member.setUsername(txtUsername.getText());
    member.setPassword(String.valueOf(txtPassword.getPassword()));

   MemberService service = new MemberService();

String result = service.addMember(member);

if (result.equals("SUCCESS")) {

    JOptionPane.showMessageDialog(this, "Member added successfully!");

    clearFields();
      loadMemberTable();

} else {

    JOptionPane.showMessageDialog(this, result);

}
   
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
         clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tblMembersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMembersMouseClicked
        // TODO add your handling code here:
         int row = tblMembers.getSelectedRow();

    selectedMemberId = Integer.parseInt(
            tblMembers.getValueAt(row, 0).toString());

    txtFullName.setText(
            tblMembers.getValueAt(row, 1).toString());

    txtEmail.setText(
            tblMembers.getValueAt(row, 2).toString());

    txtPhone.setText(
            tblMembers.getValueAt(row, 3).toString());

    txtPosition.setText(
            tblMembers.getValueAt(row, 4).toString());

    txtUsername.setText(
            tblMembers.getValueAt(row, 5).toString());
    
            btnAdd.setEnabled(false);
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
    }//GEN-LAST:event_tblMembersMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblMembers;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
